# Generated by Django 2.2.4 on 2019-12-09 07:26

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contract',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('creation_date', models.DateTimeField(verbose_name='creation date')),
                ('edited_date', models.DateTimeField(verbose_name='edited date')),
                ('created_by', models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Contract_Created_By_User_FK', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('address', models.CharField(max_length=300)),
                ('phone', models.IntegerField()),
                ('email', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='NSCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ns_number', models.IntegerField()),
                ('name', models.CharField(max_length=200)),
                ('parent_category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KontraktApp.NSCategory')),
            ],
        ),
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('default_description', models.CharField(max_length=200)),
                ('default_price_per_hour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('default_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ns_number', models.IntegerField()),
                ('NSCategory', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KontraktApp.NSCategory')),
            ],
        ),
        migrations.CreateModel(
            name='ContractItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_description', models.CharField(max_length=200)),
                ('custom_price_per_hour', models.DecimalField(decimal_places=2, max_digits=5)),
                ('custom_time', models.DecimalField(decimal_places=2, max_digits=5)),
                ('contract', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='KontraktApp.Contract')),
                ('job', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KontraktApp.Job')),
            ],
        ),
        migrations.AddField(
            model_name='contract',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='KontraktApp.Customer'),
        ),
        migrations.AddField(
            model_name='contract',
            name='edited_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='Contract_Edited_By_User_FK', to=settings.AUTH_USER_MODEL),
        ),
    ]
